//DISPLAY HOME MENU
    //ASK PLAYER IF THEY WANT TO BEGIN GAME
        //BUTTON
        //ON CLICK, BEGIN GAME
    //ASK PLAYER IF THEY WANT TO SEE ALL SCORES IN RECORD
        //BUTTON
        //ON CLICK, DISPLAY SCOREBOARD

//START GAME WHEN I PUSH "GAME START"
    //BEGIN COUNTDOWN TIMER
        //IF TIMER RUNS OUT, GAME IS OVER
    //RANDOMIZE ORDER FROM LIST OF QUESTIONS
        //CREATE ARRAY LIST OF QUESTIONS
            //1)EACH QUESTION IS ITS OWN ARRAY
                //ARRAY[0] IS THE QUESTION
                //ARRAY[1-5] ARE THE CHOICES
                //ARRAY[6] IS THE CORRECT ANSWER
            //2)MAKE AN ARRAY OF ALL QUESTIONS
                //CAN PROBABLY MAKE A FOR LOOP TO ASSEMBLE THIS
            //3)MAKE A SECOND ARRAY THAT RANDOMIZES THE QUESTIONS ARRAY
                //THIS IS THE ORDER OF OUR QUESTIONS FOR THIS RUN
        
    //DISPLAY 1 QUESTION AT A TIME
        //PLAYER CAN CHOOSE 1 OF 4 ANSWERS
        //IF PLAYER IS CORRECT, +1 TO SCORE.  IF THEY ARE WRONG, +0 TO SCORE.
        //DISPLAY NEXT QUESTION FROM ARRAY

    //WHEN ALL QUESTIONS ARE DONE, END GAME & TIMER

    //PROCEED TO SCOREBOARD

//DISPLAY SCOREBOARD WHEN FINAL QUESTION IS ANSWERED
    //DISPLAY PLAYER'S SCORE
    //CHECK IF SCORE IS BEST IN RECORD
        //IF YES, DISPLAY IT AS NEW HIGH SCORE
    //ASK PLAYER TO ENTER NAME FOR SCORE
        //NEED: INPUT & BUTTON
        //INPUT:
            //ENTER NAME HERE
        //BUTTON:
            //CLICK BUTTON TO SUBMIT NAME
        //SAVE SUBMITTED NAME TO LOCAL STORAGE
            //CREATE A RECORD OF STORED SCORES
    //DISPLAY ALL SCORES IN RECORD
    
    //ASK PLAYER IF THEY WANT TO HOME MENU
        //BUTTON
        //IF YES, DISPLAY HOME MENU
    //ASK PLAYER IF THEY WANT TO CLEAR THEIR RECORD
        //BUTTON
        //IF YES, DELETE ALL SCORES IN RECORD



//
